{
 "title": "FUNCIONO YGRAFICA VAMOO",
 "description": "priemera prueba funcionando, no sabia como guardar 2 cosas buenas de una",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Temperatura Ambiental",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"te\")"
    }
   ]
  },
  {
   "title": "Grafico Material Particulado 0.1 - 2.5 - 10",
   "type": "timeseries",
   "description": "Este grafico muestra en tiempo real como cambia el MP ",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"p01\")"
    },
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"p25\")"
    },
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"p10\")"
    }
   ]
  },
  {
   "title": "Grafico MP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"p01\")"
    }
   ]
  },
  {
   "title": "Humedad Relativa",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"hr\")"
    }
   ]
  },
  {
   "title": "Grafico MP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"p25\")"
    }
   ]
  },
  {
   "title": "Histograma MP 0.1 - 10",
   "type": "bargauge",
   "description": "En este grafico se pueden ver los histogramas de los materiales particulados de 01 - 10 m/g^3",
   "gridPos": { "h": 9, "w": 11, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"h01\")"
    },
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"h03\")"
    },
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"h05\")"
    },
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"h01\")"
    },
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"h25\")"
    },
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"h50\")"
    },
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"h10\")"
    }
   ]
  },
  {
   "title": "Presion Atmosferica",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"pa\")"
    }
   ]
  },
  {
   "title": "Grafico MP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Interfaces\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"p10\")"
    }
   ]
  }
 ]
}